COMMAND_COLOR_IN_HELP = 'blue'
FIELD_COLOR_IN_LOG_IN = 'blue'
FIELD_COLOR_IN_SIGN_UP = 'blue'
COLOR_IN_EXIT = 'red'
COLOR_IN_LOGIN_OR_SIGNUP = 'blue'
CHOICE_FOR_LOGIN_IN_CHOOSE_LOGIN_OR_SIGNUP = '1'
CHOICE_FOR_SIGNUP_IN_CHOOSE_LOGIN_OR_SIGNUP = '2'

INVALID_OPTION_TEXT_COLOR = 'red'
VALID_LOGIN_OR_SIGNUP_RETURNED_VALUE = 0
INVALID_LOGIN_RETURNED_VALUE = 1
INVALID_SIGHNUP_RETURNED_VALUE = 2
INVALID_CHOICE_RETURNED_VALUE = 3
